# Generated by Django 4.1 on 2022-09-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rec_Season', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='enrolment',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='imgmember',
            name='enrolment',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
    ]
