# Generated by Django 4.1 on 2022-09-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rec_Season', '0002_alter_candidate_enrolment_alter_imgmember_enrolment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='current_year',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='imgmember',
            name='current_year',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
    ]
