# Generated by Django 4.1 on 2022-10-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rec_Season', '0003_alter_candidate_current_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='current_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='enrolment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imgmember',
            name='current_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imgmember',
            name='enrolment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='role',
            field=models.CharField(choices=[('1yDev', '1stYear Developers'), ('2yDev', '2ndYear Developer'), ('Des', 'Designer')], max_length=20),
        ),
        migrations.DeleteModel(
            name='IMGMemberSeasonData',
        ),
    ]
