# Generated by Django 4.1 on 2022-10-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rec_Season', '0005_alter_candidate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='branch',
            field=models.CharField(default='CSE', max_length=200),
            preserve_default=False,
        ),
    ]
