# Generated by Django 4.1 on 2022-10-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rec_Season', '0006_candidate_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
