# Generated by Django 4.1 on 2022-10-13 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rec_Season', '0009_alter_testresponse_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rec_Season.candidateseasondata'),
        ),
    ]
