# Generated by Django 4.1 on 2022-10-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rec_Season', '0010_alter_interview_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewresponse',
            name='section',
        ),
    ]
