# Generated by Django 4.1 on 2022-10-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rec_Season', '0015_remove_paper_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='slot_timing',
        ),
    ]
