# Generated by Django 4.1 on 2022-10-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rec_Season', '0017_interview_slot_timing_paper_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='call_notes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('C', 'Called'), ('N', 'Not Called'), ('O', 'Ongoing'), ('W', 'Waiting'), ('D', 'Done')], max_length=10, null=True),
        ),
    ]
