# Generated by Django 4.1 on 2022-10-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rec_Season', '0018_alter_interview_call_notes_alter_interview_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewpanel',
            name='interview_type',
        ),
    ]
