# Generated by Django 4.1 on 2022-10-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rec_Season', '0019_remove_interviewpanel_interview_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewrounds',
            name='latest_interview_candidate',
            field=models.ManyToManyField(blank=True, null=True, to='Rec_Season.candidateseasondata'),
        ),
    ]
