# Generated by Django 4.1 on 2022-11-23 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rec_Season', '0023_remove_interviewpanel_interview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewpanel',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rec_Season.season'),
        ),
    ]
