# dont forget to run python3 manage.py migrate inside the backend container after docker-compose build
services:
  database:
    container_name: database_container
    image: mysql
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=Rose!1234
      - MYSQL_ROOT_HOST=
      - MYSQL_HOST=
      - MYSQL_DATABASE=Recruitment_Season
      - MYSQL_USER=rishi
      - MYSQL_PASSWORD=Rose!1234
    networks:
      - net-name
    # restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - backend-volume:/var/lib/mysql/

  backend:
    container_name: backend_container
    build:
      context: ./backend/autumn
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - net-name
    depends_on:
      - database
    restart: always
    # command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate"
    # command: python3 manage.py migrate

  frontend:
    container_name: frontend_container
    build:
      context: ./frontend/rec_season
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - net-name
  

networks:
  net-name:
volumes:
  backend-volume: