services:
  database:
    image: mysql
    expose:
      - 3306
    environment:
      # - MYSQL_ROOT_PASSWORD=Rose!1234
      # - MYSQL_ROOT_HOST=
      # - MYSQL_HOST=
      - MYSQL_DATABASE=Recruitment_Season
      - MYSQL_USER=rishi
      - MYSQL_PASSWORD=Rose!1234
    networks:
      - net-name
    # restart: always
    # command: mysqld --default-authentication-plugin=mysql_native_password
  backend:
    build:
      context: ./backend/autumn
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - net-name
    depends_on:
      - database
    # restart: always
  frontend:
    build:
      context: ./frontend/rec_season
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - net-name
  

networks:
  net-name: